name: Publicar Doc con docfx

on: push
jobs:
  docfx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Install DocFx tool
        run: dotnet tool update -g docfx

      - name: Generar metadata con DocFx
        run: docfx metadata Bank/docfx.json

      - name: Construir sitio de documentación
        run: docfx build Bank/docfx.json

      - name: Subir documentación a una nueva rama (gh-pages-docs)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Bank/_site
          publish_branch: gh-pages-docs  # Cambié el nombre de la rama a gh-pages-docs